//
// Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
//
// On Fri Mar 22 16:10:17 IST 2019
//
//
// Ports:
// Name                         I/O  size props
// c2b                            O     5 reg
// nodeId                         I     8 unused
// CLK                            I     1 clock
// RST_N                          I     1 unused
// b2c_x                          I     7 reg
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCheckNode_7_5(nodeId,
		       CLK,
		       RST_N,

		       b2c_x,

		       c2b);
  input  [7 : 0] nodeId;
  input  CLK;
  input  RST_N;

  // action method b2c
  input  [6 : 0] b2c_x;

  // value method c2b
  output [4 : 0] c2b;

  // signals for module outputs
  wire [4 : 0] c2b;

  // register rg_y
  reg [4 : 0] rg_y;
  wire [4 : 0] rg_y$D_IN;
  wire rg_y$EN;

  // rule scheduling signals
  wire CAN_FIRE_b2c, WILL_FIRE_b2c;

  // action method b2c
  assign CAN_FIRE_b2c = 1'd1 ;
  assign WILL_FIRE_b2c = 1'd1 ;

  // value method c2b
  assign c2b = rg_y ;

  // register rg_y
  assign rg_y$D_IN = b2c_x[4:0] ;
  assign rg_y$EN = 1'd1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (rg_y$EN) rg_y <= `BSV_ASSIGNMENT_DELAY rg_y$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    rg_y = 5'h0A;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkCheckNode_7_5

