//
// Generated by Bluespec Compiler, version 2018.10.beta1 (build e1df8052c, 2018-10-17)
//
// On Tue Apr 16 14:00:56 IST 2019
//
//
// Ports:
// Name                         I/O  size props
// RDY_request_put                O     1 reg
// response_get                   O    28 reg
// RDY_response_get               O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// request_put                    I    28 reg
// EN_request_put                 I     1
// EN_response_get                I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkLdpcCore(CLK,
		  RST_N,

		  request_put,
		  EN_request_put,
		  RDY_request_put,

		  EN_response_get,
		  response_get,
		  RDY_response_get);
  input  CLK;
  input  RST_N;

  // action method request_put
  input  [27 : 0] request_put;
  input  EN_request_put;
  output RDY_request_put;

  // actionvalue method response_get
  input  EN_response_get;
  output [27 : 0] response_get;
  output RDY_response_get;

  // signals for module outputs
  wire [27 : 0] response_get;
  wire RDY_request_put, RDY_response_get;

  // ports of submodule ffI
  wire [27 : 0] ffI$D_IN, ffI$D_OUT;
  wire ffI$CLR, ffI$DEQ, ffI$EMPTY_N, ffI$ENQ, ffI$FULL_N;

  // ports of submodule ffO
  wire [27 : 0] ffO$D_IN, ffO$D_OUT;
  wire ffO$CLR, ffO$DEQ, ffO$EMPTY_N, ffO$ENQ, ffO$FULL_N;

  // ports of submodule vBitNodes_0
  wire [3 : 0] vBitNodes_0$b2c_get,
	       vBitNodes_0$c2b_0_put,
	       vBitNodes_0$c2b_1_put,
	       vBitNodes_0$c2b_2_put,
	       vBitNodes_0$codeIn_put,
	       vBitNodes_0$dataOut_get;
  wire vBitNodes_0$EN_b2c_get,
       vBitNodes_0$EN_c2b_0_put,
       vBitNodes_0$EN_c2b_1_put,
       vBitNodes_0$EN_c2b_2_put,
       vBitNodes_0$EN_codeIn_put,
       vBitNodes_0$EN_dataOut_get,
       vBitNodes_0$RDY_b2c_get,
       vBitNodes_0$RDY_c2b_0_put,
       vBitNodes_0$RDY_c2b_1_put,
       vBitNodes_0$RDY_c2b_2_put,
       vBitNodes_0$RDY_codeIn_put,
       vBitNodes_0$RDY_dataOut_get;

  // ports of submodule vBitNodes_1
  wire [3 : 0] vBitNodes_1$b2c_get,
	       vBitNodes_1$c2b_0_put,
	       vBitNodes_1$c2b_1_put,
	       vBitNodes_1$c2b_2_put,
	       vBitNodes_1$codeIn_put,
	       vBitNodes_1$dataOut_get;
  wire vBitNodes_1$EN_b2c_get,
       vBitNodes_1$EN_c2b_0_put,
       vBitNodes_1$EN_c2b_1_put,
       vBitNodes_1$EN_c2b_2_put,
       vBitNodes_1$EN_codeIn_put,
       vBitNodes_1$EN_dataOut_get,
       vBitNodes_1$RDY_b2c_get,
       vBitNodes_1$RDY_c2b_0_put,
       vBitNodes_1$RDY_c2b_1_put,
       vBitNodes_1$RDY_c2b_2_put,
       vBitNodes_1$RDY_codeIn_put,
       vBitNodes_1$RDY_dataOut_get;

  // ports of submodule vBitNodes_2
  wire [3 : 0] vBitNodes_2$b2c_get,
	       vBitNodes_2$c2b_0_put,
	       vBitNodes_2$c2b_1_put,
	       vBitNodes_2$c2b_2_put,
	       vBitNodes_2$codeIn_put,
	       vBitNodes_2$dataOut_get;
  wire vBitNodes_2$EN_b2c_get,
       vBitNodes_2$EN_c2b_0_put,
       vBitNodes_2$EN_c2b_1_put,
       vBitNodes_2$EN_c2b_2_put,
       vBitNodes_2$EN_codeIn_put,
       vBitNodes_2$EN_dataOut_get,
       vBitNodes_2$RDY_b2c_get,
       vBitNodes_2$RDY_c2b_0_put,
       vBitNodes_2$RDY_c2b_1_put,
       vBitNodes_2$RDY_c2b_2_put,
       vBitNodes_2$RDY_codeIn_put,
       vBitNodes_2$RDY_dataOut_get;

  // ports of submodule vBitNodes_3
  wire [3 : 0] vBitNodes_3$b2c_get,
	       vBitNodes_3$c2b_0_put,
	       vBitNodes_3$c2b_1_put,
	       vBitNodes_3$c2b_2_put,
	       vBitNodes_3$codeIn_put,
	       vBitNodes_3$dataOut_get;
  wire vBitNodes_3$EN_b2c_get,
       vBitNodes_3$EN_c2b_0_put,
       vBitNodes_3$EN_c2b_1_put,
       vBitNodes_3$EN_c2b_2_put,
       vBitNodes_3$EN_codeIn_put,
       vBitNodes_3$EN_dataOut_get,
       vBitNodes_3$RDY_b2c_get,
       vBitNodes_3$RDY_c2b_0_put,
       vBitNodes_3$RDY_c2b_1_put,
       vBitNodes_3$RDY_c2b_2_put,
       vBitNodes_3$RDY_codeIn_put,
       vBitNodes_3$RDY_dataOut_get;

  // ports of submodule vBitNodes_4
  wire [3 : 0] vBitNodes_4$b2c_get,
	       vBitNodes_4$c2b_0_put,
	       vBitNodes_4$c2b_1_put,
	       vBitNodes_4$c2b_2_put,
	       vBitNodes_4$codeIn_put,
	       vBitNodes_4$dataOut_get;
  wire vBitNodes_4$EN_b2c_get,
       vBitNodes_4$EN_c2b_0_put,
       vBitNodes_4$EN_c2b_1_put,
       vBitNodes_4$EN_c2b_2_put,
       vBitNodes_4$EN_codeIn_put,
       vBitNodes_4$EN_dataOut_get,
       vBitNodes_4$RDY_b2c_get,
       vBitNodes_4$RDY_c2b_0_put,
       vBitNodes_4$RDY_c2b_1_put,
       vBitNodes_4$RDY_c2b_2_put,
       vBitNodes_4$RDY_codeIn_put,
       vBitNodes_4$RDY_dataOut_get;

  // ports of submodule vBitNodes_5
  wire [3 : 0] vBitNodes_5$b2c_get,
	       vBitNodes_5$c2b_0_put,
	       vBitNodes_5$c2b_1_put,
	       vBitNodes_5$c2b_2_put,
	       vBitNodes_5$codeIn_put,
	       vBitNodes_5$dataOut_get;
  wire vBitNodes_5$EN_b2c_get,
       vBitNodes_5$EN_c2b_0_put,
       vBitNodes_5$EN_c2b_1_put,
       vBitNodes_5$EN_c2b_2_put,
       vBitNodes_5$EN_codeIn_put,
       vBitNodes_5$EN_dataOut_get,
       vBitNodes_5$RDY_b2c_get,
       vBitNodes_5$RDY_c2b_0_put,
       vBitNodes_5$RDY_c2b_1_put,
       vBitNodes_5$RDY_c2b_2_put,
       vBitNodes_5$RDY_codeIn_put,
       vBitNodes_5$RDY_dataOut_get;

  // ports of submodule vBitNodes_6
  wire [3 : 0] vBitNodes_6$b2c_get,
	       vBitNodes_6$c2b_0_put,
	       vBitNodes_6$c2b_1_put,
	       vBitNodes_6$c2b_2_put,
	       vBitNodes_6$codeIn_put,
	       vBitNodes_6$dataOut_get;
  wire vBitNodes_6$EN_b2c_get,
       vBitNodes_6$EN_c2b_0_put,
       vBitNodes_6$EN_c2b_1_put,
       vBitNodes_6$EN_c2b_2_put,
       vBitNodes_6$EN_codeIn_put,
       vBitNodes_6$EN_dataOut_get,
       vBitNodes_6$RDY_b2c_get,
       vBitNodes_6$RDY_c2b_0_put,
       vBitNodes_6$RDY_c2b_1_put,
       vBitNodes_6$RDY_c2b_2_put,
       vBitNodes_6$RDY_codeIn_put,
       vBitNodes_6$RDY_dataOut_get;

  // ports of submodule vCheckNodes_0
  wire [3 : 0] vCheckNodes_0$b2c_0_put,
	       vCheckNodes_0$b2c_1_put,
	       vCheckNodes_0$b2c_2_put,
	       vCheckNodes_0$c2b_get;
  wire vCheckNodes_0$EN_b2c_0_put,
       vCheckNodes_0$EN_b2c_1_put,
       vCheckNodes_0$EN_b2c_2_put,
       vCheckNodes_0$EN_c2b_get,
       vCheckNodes_0$RDY_b2c_0_put,
       vCheckNodes_0$RDY_b2c_1_put,
       vCheckNodes_0$RDY_b2c_2_put,
       vCheckNodes_0$RDY_c2b_get;

  // ports of submodule vCheckNodes_1
  wire [3 : 0] vCheckNodes_1$b2c_0_put,
	       vCheckNodes_1$b2c_1_put,
	       vCheckNodes_1$b2c_2_put,
	       vCheckNodes_1$c2b_get;
  wire vCheckNodes_1$EN_b2c_0_put,
       vCheckNodes_1$EN_b2c_1_put,
       vCheckNodes_1$EN_b2c_2_put,
       vCheckNodes_1$EN_c2b_get,
       vCheckNodes_1$RDY_b2c_0_put,
       vCheckNodes_1$RDY_b2c_1_put,
       vCheckNodes_1$RDY_b2c_2_put,
       vCheckNodes_1$RDY_c2b_get;

  // ports of submodule vCheckNodes_2
  wire [3 : 0] vCheckNodes_2$b2c_0_put,
	       vCheckNodes_2$b2c_1_put,
	       vCheckNodes_2$b2c_2_put,
	       vCheckNodes_2$c2b_get;
  wire vCheckNodes_2$EN_b2c_0_put,
       vCheckNodes_2$EN_b2c_1_put,
       vCheckNodes_2$EN_b2c_2_put,
       vCheckNodes_2$EN_c2b_get,
       vCheckNodes_2$RDY_b2c_0_put,
       vCheckNodes_2$RDY_b2c_1_put,
       vCheckNodes_2$RDY_b2c_2_put,
       vCheckNodes_2$RDY_c2b_get;

  // ports of submodule vCheckNodes_3
  wire [3 : 0] vCheckNodes_3$b2c_0_put,
	       vCheckNodes_3$b2c_1_put,
	       vCheckNodes_3$b2c_2_put,
	       vCheckNodes_3$c2b_get;
  wire vCheckNodes_3$EN_b2c_0_put,
       vCheckNodes_3$EN_b2c_1_put,
       vCheckNodes_3$EN_b2c_2_put,
       vCheckNodes_3$EN_c2b_get,
       vCheckNodes_3$RDY_b2c_0_put,
       vCheckNodes_3$RDY_b2c_1_put,
       vCheckNodes_3$RDY_b2c_2_put,
       vCheckNodes_3$RDY_c2b_get;

  // ports of submodule vCheckNodes_4
  wire [3 : 0] vCheckNodes_4$b2c_0_put,
	       vCheckNodes_4$b2c_1_put,
	       vCheckNodes_4$b2c_2_put,
	       vCheckNodes_4$c2b_get;
  wire vCheckNodes_4$EN_b2c_0_put,
       vCheckNodes_4$EN_b2c_1_put,
       vCheckNodes_4$EN_b2c_2_put,
       vCheckNodes_4$EN_c2b_get,
       vCheckNodes_4$RDY_b2c_0_put,
       vCheckNodes_4$RDY_b2c_1_put,
       vCheckNodes_4$RDY_b2c_2_put,
       vCheckNodes_4$RDY_c2b_get;

  // ports of submodule vCheckNodes_5
  wire [3 : 0] vCheckNodes_5$b2c_0_put,
	       vCheckNodes_5$b2c_1_put,
	       vCheckNodes_5$b2c_2_put,
	       vCheckNodes_5$c2b_get;
  wire vCheckNodes_5$EN_b2c_0_put,
       vCheckNodes_5$EN_b2c_1_put,
       vCheckNodes_5$EN_b2c_2_put,
       vCheckNodes_5$EN_c2b_get,
       vCheckNodes_5$RDY_b2c_0_put,
       vCheckNodes_5$RDY_b2c_1_put,
       vCheckNodes_5$RDY_b2c_2_put,
       vCheckNodes_5$RDY_c2b_get;

  // ports of submodule vCheckNodes_6
  wire [3 : 0] vCheckNodes_6$b2c_0_put,
	       vCheckNodes_6$b2c_1_put,
	       vCheckNodes_6$b2c_2_put,
	       vCheckNodes_6$c2b_get;
  wire vCheckNodes_6$EN_b2c_0_put,
       vCheckNodes_6$EN_b2c_1_put,
       vCheckNodes_6$EN_b2c_2_put,
       vCheckNodes_6$EN_c2b_get,
       vCheckNodes_6$RDY_b2c_0_put,
       vCheckNodes_6$RDY_b2c_1_put,
       vCheckNodes_6$RDY_b2c_2_put,
       vCheckNodes_6$RDY_c2b_get;

  // rule scheduling signals
  wire CAN_FIRE_RL_rlConnect,
       CAN_FIRE_RL_rlConnect_1,
       CAN_FIRE_RL_rlConnect_10,
       CAN_FIRE_RL_rlConnect_11,
       CAN_FIRE_RL_rlConnect_12,
       CAN_FIRE_RL_rlConnect_13,
       CAN_FIRE_RL_rlConnect_2,
       CAN_FIRE_RL_rlConnect_3,
       CAN_FIRE_RL_rlConnect_4,
       CAN_FIRE_RL_rlConnect_5,
       CAN_FIRE_RL_rlConnect_6,
       CAN_FIRE_RL_rlConnect_7,
       CAN_FIRE_RL_rlConnect_8,
       CAN_FIRE_RL_rlConnect_9,
       CAN_FIRE_RL_rlGetDecodedWordOut,
       CAN_FIRE_RL_rlPutCodeWordIn,
       CAN_FIRE_request_put,
       CAN_FIRE_response_get,
       WILL_FIRE_RL_rlConnect,
       WILL_FIRE_RL_rlConnect_1,
       WILL_FIRE_RL_rlConnect_10,
       WILL_FIRE_RL_rlConnect_11,
       WILL_FIRE_RL_rlConnect_12,
       WILL_FIRE_RL_rlConnect_13,
       WILL_FIRE_RL_rlConnect_2,
       WILL_FIRE_RL_rlConnect_3,
       WILL_FIRE_RL_rlConnect_4,
       WILL_FIRE_RL_rlConnect_5,
       WILL_FIRE_RL_rlConnect_6,
       WILL_FIRE_RL_rlConnect_7,
       WILL_FIRE_RL_rlConnect_8,
       WILL_FIRE_RL_rlConnect_9,
       WILL_FIRE_RL_rlGetDecodedWordOut,
       WILL_FIRE_RL_rlPutCodeWordIn,
       WILL_FIRE_request_put,
       WILL_FIRE_response_get;

  // remaining internal signals
  wire vBitNodes_1_RDY_codeIn_put__14_AND_vBitNodes_2_ETC___d126,
       vBitNodes_1_RDY_dataOut_get__37_AND_vBitNodes__ETC___d149;

  // action method request_put
  assign RDY_request_put = ffI$FULL_N ;
  assign CAN_FIRE_request_put = ffI$FULL_N ;
  assign WILL_FIRE_request_put = EN_request_put ;

  // actionvalue method response_get
  assign response_get = ffO$D_OUT ;
  assign RDY_response_get = ffO$EMPTY_N ;
  assign CAN_FIRE_response_get = ffO$EMPTY_N ;
  assign WILL_FIRE_response_get = EN_response_get ;

  // submodule ffI
  FIFO2 #(.width(32'd28), .guarded(32'd1)) ffI(.RST(RST_N),
					       .CLK(CLK),
					       .D_IN(ffI$D_IN),
					       .ENQ(ffI$ENQ),
					       .DEQ(ffI$DEQ),
					       .CLR(ffI$CLR),
					       .D_OUT(ffI$D_OUT),
					       .FULL_N(ffI$FULL_N),
					       .EMPTY_N(ffI$EMPTY_N));

  // submodule ffO
  FIFO2 #(.width(32'd28), .guarded(32'd1)) ffO(.RST(RST_N),
					       .CLK(CLK),
					       .D_IN(ffO$D_IN),
					       .ENQ(ffO$ENQ),
					       .DEQ(ffO$DEQ),
					       .CLR(ffO$CLR),
					       .D_OUT(ffO$D_OUT),
					       .FULL_N(ffO$FULL_N),
					       .EMPTY_N(ffO$EMPTY_N));

  // submodule vBitNodes_0
  mkBitNode vBitNodes_0(.CLK(CLK),
			.RST_N(RST_N),
			.c2b_0_put(vBitNodes_0$c2b_0_put),
			.c2b_1_put(vBitNodes_0$c2b_1_put),
			.c2b_2_put(vBitNodes_0$c2b_2_put),
			.codeIn_put(vBitNodes_0$codeIn_put),
			.EN_c2b_0_put(vBitNodes_0$EN_c2b_0_put),
			.EN_c2b_1_put(vBitNodes_0$EN_c2b_1_put),
			.EN_c2b_2_put(vBitNodes_0$EN_c2b_2_put),
			.EN_b2c_get(vBitNodes_0$EN_b2c_get),
			.EN_codeIn_put(vBitNodes_0$EN_codeIn_put),
			.EN_dataOut_get(vBitNodes_0$EN_dataOut_get),
			.RDY_c2b_0_put(vBitNodes_0$RDY_c2b_0_put),
			.RDY_c2b_1_put(vBitNodes_0$RDY_c2b_1_put),
			.RDY_c2b_2_put(vBitNodes_0$RDY_c2b_2_put),
			.b2c_get(vBitNodes_0$b2c_get),
			.RDY_b2c_get(vBitNodes_0$RDY_b2c_get),
			.RDY_codeIn_put(vBitNodes_0$RDY_codeIn_put),
			.dataOut_get(vBitNodes_0$dataOut_get),
			.RDY_dataOut_get(vBitNodes_0$RDY_dataOut_get));

  // submodule vBitNodes_1
  mkBitNode vBitNodes_1(.CLK(CLK),
			.RST_N(RST_N),
			.c2b_0_put(vBitNodes_1$c2b_0_put),
			.c2b_1_put(vBitNodes_1$c2b_1_put),
			.c2b_2_put(vBitNodes_1$c2b_2_put),
			.codeIn_put(vBitNodes_1$codeIn_put),
			.EN_c2b_0_put(vBitNodes_1$EN_c2b_0_put),
			.EN_c2b_1_put(vBitNodes_1$EN_c2b_1_put),
			.EN_c2b_2_put(vBitNodes_1$EN_c2b_2_put),
			.EN_b2c_get(vBitNodes_1$EN_b2c_get),
			.EN_codeIn_put(vBitNodes_1$EN_codeIn_put),
			.EN_dataOut_get(vBitNodes_1$EN_dataOut_get),
			.RDY_c2b_0_put(vBitNodes_1$RDY_c2b_0_put),
			.RDY_c2b_1_put(vBitNodes_1$RDY_c2b_1_put),
			.RDY_c2b_2_put(vBitNodes_1$RDY_c2b_2_put),
			.b2c_get(vBitNodes_1$b2c_get),
			.RDY_b2c_get(vBitNodes_1$RDY_b2c_get),
			.RDY_codeIn_put(vBitNodes_1$RDY_codeIn_put),
			.dataOut_get(vBitNodes_1$dataOut_get),
			.RDY_dataOut_get(vBitNodes_1$RDY_dataOut_get));

  // submodule vBitNodes_2
  mkBitNode vBitNodes_2(.CLK(CLK),
			.RST_N(RST_N),
			.c2b_0_put(vBitNodes_2$c2b_0_put),
			.c2b_1_put(vBitNodes_2$c2b_1_put),
			.c2b_2_put(vBitNodes_2$c2b_2_put),
			.codeIn_put(vBitNodes_2$codeIn_put),
			.EN_c2b_0_put(vBitNodes_2$EN_c2b_0_put),
			.EN_c2b_1_put(vBitNodes_2$EN_c2b_1_put),
			.EN_c2b_2_put(vBitNodes_2$EN_c2b_2_put),
			.EN_b2c_get(vBitNodes_2$EN_b2c_get),
			.EN_codeIn_put(vBitNodes_2$EN_codeIn_put),
			.EN_dataOut_get(vBitNodes_2$EN_dataOut_get),
			.RDY_c2b_0_put(vBitNodes_2$RDY_c2b_0_put),
			.RDY_c2b_1_put(vBitNodes_2$RDY_c2b_1_put),
			.RDY_c2b_2_put(vBitNodes_2$RDY_c2b_2_put),
			.b2c_get(vBitNodes_2$b2c_get),
			.RDY_b2c_get(vBitNodes_2$RDY_b2c_get),
			.RDY_codeIn_put(vBitNodes_2$RDY_codeIn_put),
			.dataOut_get(vBitNodes_2$dataOut_get),
			.RDY_dataOut_get(vBitNodes_2$RDY_dataOut_get));

  // submodule vBitNodes_3
  mkBitNode vBitNodes_3(.CLK(CLK),
			.RST_N(RST_N),
			.c2b_0_put(vBitNodes_3$c2b_0_put),
			.c2b_1_put(vBitNodes_3$c2b_1_put),
			.c2b_2_put(vBitNodes_3$c2b_2_put),
			.codeIn_put(vBitNodes_3$codeIn_put),
			.EN_c2b_0_put(vBitNodes_3$EN_c2b_0_put),
			.EN_c2b_1_put(vBitNodes_3$EN_c2b_1_put),
			.EN_c2b_2_put(vBitNodes_3$EN_c2b_2_put),
			.EN_b2c_get(vBitNodes_3$EN_b2c_get),
			.EN_codeIn_put(vBitNodes_3$EN_codeIn_put),
			.EN_dataOut_get(vBitNodes_3$EN_dataOut_get),
			.RDY_c2b_0_put(vBitNodes_3$RDY_c2b_0_put),
			.RDY_c2b_1_put(vBitNodes_3$RDY_c2b_1_put),
			.RDY_c2b_2_put(vBitNodes_3$RDY_c2b_2_put),
			.b2c_get(vBitNodes_3$b2c_get),
			.RDY_b2c_get(vBitNodes_3$RDY_b2c_get),
			.RDY_codeIn_put(vBitNodes_3$RDY_codeIn_put),
			.dataOut_get(vBitNodes_3$dataOut_get),
			.RDY_dataOut_get(vBitNodes_3$RDY_dataOut_get));

  // submodule vBitNodes_4
  mkBitNode vBitNodes_4(.CLK(CLK),
			.RST_N(RST_N),
			.c2b_0_put(vBitNodes_4$c2b_0_put),
			.c2b_1_put(vBitNodes_4$c2b_1_put),
			.c2b_2_put(vBitNodes_4$c2b_2_put),
			.codeIn_put(vBitNodes_4$codeIn_put),
			.EN_c2b_0_put(vBitNodes_4$EN_c2b_0_put),
			.EN_c2b_1_put(vBitNodes_4$EN_c2b_1_put),
			.EN_c2b_2_put(vBitNodes_4$EN_c2b_2_put),
			.EN_b2c_get(vBitNodes_4$EN_b2c_get),
			.EN_codeIn_put(vBitNodes_4$EN_codeIn_put),
			.EN_dataOut_get(vBitNodes_4$EN_dataOut_get),
			.RDY_c2b_0_put(vBitNodes_4$RDY_c2b_0_put),
			.RDY_c2b_1_put(vBitNodes_4$RDY_c2b_1_put),
			.RDY_c2b_2_put(vBitNodes_4$RDY_c2b_2_put),
			.b2c_get(vBitNodes_4$b2c_get),
			.RDY_b2c_get(vBitNodes_4$RDY_b2c_get),
			.RDY_codeIn_put(vBitNodes_4$RDY_codeIn_put),
			.dataOut_get(vBitNodes_4$dataOut_get),
			.RDY_dataOut_get(vBitNodes_4$RDY_dataOut_get));

  // submodule vBitNodes_5
  mkBitNode vBitNodes_5(.CLK(CLK),
			.RST_N(RST_N),
			.c2b_0_put(vBitNodes_5$c2b_0_put),
			.c2b_1_put(vBitNodes_5$c2b_1_put),
			.c2b_2_put(vBitNodes_5$c2b_2_put),
			.codeIn_put(vBitNodes_5$codeIn_put),
			.EN_c2b_0_put(vBitNodes_5$EN_c2b_0_put),
			.EN_c2b_1_put(vBitNodes_5$EN_c2b_1_put),
			.EN_c2b_2_put(vBitNodes_5$EN_c2b_2_put),
			.EN_b2c_get(vBitNodes_5$EN_b2c_get),
			.EN_codeIn_put(vBitNodes_5$EN_codeIn_put),
			.EN_dataOut_get(vBitNodes_5$EN_dataOut_get),
			.RDY_c2b_0_put(vBitNodes_5$RDY_c2b_0_put),
			.RDY_c2b_1_put(vBitNodes_5$RDY_c2b_1_put),
			.RDY_c2b_2_put(vBitNodes_5$RDY_c2b_2_put),
			.b2c_get(vBitNodes_5$b2c_get),
			.RDY_b2c_get(vBitNodes_5$RDY_b2c_get),
			.RDY_codeIn_put(vBitNodes_5$RDY_codeIn_put),
			.dataOut_get(vBitNodes_5$dataOut_get),
			.RDY_dataOut_get(vBitNodes_5$RDY_dataOut_get));

  // submodule vBitNodes_6
  mkBitNode vBitNodes_6(.CLK(CLK),
			.RST_N(RST_N),
			.c2b_0_put(vBitNodes_6$c2b_0_put),
			.c2b_1_put(vBitNodes_6$c2b_1_put),
			.c2b_2_put(vBitNodes_6$c2b_2_put),
			.codeIn_put(vBitNodes_6$codeIn_put),
			.EN_c2b_0_put(vBitNodes_6$EN_c2b_0_put),
			.EN_c2b_1_put(vBitNodes_6$EN_c2b_1_put),
			.EN_c2b_2_put(vBitNodes_6$EN_c2b_2_put),
			.EN_b2c_get(vBitNodes_6$EN_b2c_get),
			.EN_codeIn_put(vBitNodes_6$EN_codeIn_put),
			.EN_dataOut_get(vBitNodes_6$EN_dataOut_get),
			.RDY_c2b_0_put(vBitNodes_6$RDY_c2b_0_put),
			.RDY_c2b_1_put(vBitNodes_6$RDY_c2b_1_put),
			.RDY_c2b_2_put(vBitNodes_6$RDY_c2b_2_put),
			.b2c_get(vBitNodes_6$b2c_get),
			.RDY_b2c_get(vBitNodes_6$RDY_b2c_get),
			.RDY_codeIn_put(vBitNodes_6$RDY_codeIn_put),
			.dataOut_get(vBitNodes_6$dataOut_get),
			.RDY_dataOut_get(vBitNodes_6$RDY_dataOut_get));

  // submodule vCheckNodes_0
  mkCheckNode vCheckNodes_0(.CLK(CLK),
			    .RST_N(RST_N),
			    .b2c_0_put(vCheckNodes_0$b2c_0_put),
			    .b2c_1_put(vCheckNodes_0$b2c_1_put),
			    .b2c_2_put(vCheckNodes_0$b2c_2_put),
			    .EN_b2c_0_put(vCheckNodes_0$EN_b2c_0_put),
			    .EN_b2c_1_put(vCheckNodes_0$EN_b2c_1_put),
			    .EN_b2c_2_put(vCheckNodes_0$EN_b2c_2_put),
			    .EN_c2b_get(vCheckNodes_0$EN_c2b_get),
			    .RDY_b2c_0_put(vCheckNodes_0$RDY_b2c_0_put),
			    .RDY_b2c_1_put(vCheckNodes_0$RDY_b2c_1_put),
			    .RDY_b2c_2_put(vCheckNodes_0$RDY_b2c_2_put),
			    .c2b_get(vCheckNodes_0$c2b_get),
			    .RDY_c2b_get(vCheckNodes_0$RDY_c2b_get));

  // submodule vCheckNodes_1
  mkCheckNode vCheckNodes_1(.CLK(CLK),
			    .RST_N(RST_N),
			    .b2c_0_put(vCheckNodes_1$b2c_0_put),
			    .b2c_1_put(vCheckNodes_1$b2c_1_put),
			    .b2c_2_put(vCheckNodes_1$b2c_2_put),
			    .EN_b2c_0_put(vCheckNodes_1$EN_b2c_0_put),
			    .EN_b2c_1_put(vCheckNodes_1$EN_b2c_1_put),
			    .EN_b2c_2_put(vCheckNodes_1$EN_b2c_2_put),
			    .EN_c2b_get(vCheckNodes_1$EN_c2b_get),
			    .RDY_b2c_0_put(vCheckNodes_1$RDY_b2c_0_put),
			    .RDY_b2c_1_put(vCheckNodes_1$RDY_b2c_1_put),
			    .RDY_b2c_2_put(vCheckNodes_1$RDY_b2c_2_put),
			    .c2b_get(vCheckNodes_1$c2b_get),
			    .RDY_c2b_get(vCheckNodes_1$RDY_c2b_get));

  // submodule vCheckNodes_2
  mkCheckNode vCheckNodes_2(.CLK(CLK),
			    .RST_N(RST_N),
			    .b2c_0_put(vCheckNodes_2$b2c_0_put),
			    .b2c_1_put(vCheckNodes_2$b2c_1_put),
			    .b2c_2_put(vCheckNodes_2$b2c_2_put),
			    .EN_b2c_0_put(vCheckNodes_2$EN_b2c_0_put),
			    .EN_b2c_1_put(vCheckNodes_2$EN_b2c_1_put),
			    .EN_b2c_2_put(vCheckNodes_2$EN_b2c_2_put),
			    .EN_c2b_get(vCheckNodes_2$EN_c2b_get),
			    .RDY_b2c_0_put(vCheckNodes_2$RDY_b2c_0_put),
			    .RDY_b2c_1_put(vCheckNodes_2$RDY_b2c_1_put),
			    .RDY_b2c_2_put(vCheckNodes_2$RDY_b2c_2_put),
			    .c2b_get(vCheckNodes_2$c2b_get),
			    .RDY_c2b_get(vCheckNodes_2$RDY_c2b_get));

  // submodule vCheckNodes_3
  mkCheckNode vCheckNodes_3(.CLK(CLK),
			    .RST_N(RST_N),
			    .b2c_0_put(vCheckNodes_3$b2c_0_put),
			    .b2c_1_put(vCheckNodes_3$b2c_1_put),
			    .b2c_2_put(vCheckNodes_3$b2c_2_put),
			    .EN_b2c_0_put(vCheckNodes_3$EN_b2c_0_put),
			    .EN_b2c_1_put(vCheckNodes_3$EN_b2c_1_put),
			    .EN_b2c_2_put(vCheckNodes_3$EN_b2c_2_put),
			    .EN_c2b_get(vCheckNodes_3$EN_c2b_get),
			    .RDY_b2c_0_put(vCheckNodes_3$RDY_b2c_0_put),
			    .RDY_b2c_1_put(vCheckNodes_3$RDY_b2c_1_put),
			    .RDY_b2c_2_put(vCheckNodes_3$RDY_b2c_2_put),
			    .c2b_get(vCheckNodes_3$c2b_get),
			    .RDY_c2b_get(vCheckNodes_3$RDY_c2b_get));

  // submodule vCheckNodes_4
  mkCheckNode vCheckNodes_4(.CLK(CLK),
			    .RST_N(RST_N),
			    .b2c_0_put(vCheckNodes_4$b2c_0_put),
			    .b2c_1_put(vCheckNodes_4$b2c_1_put),
			    .b2c_2_put(vCheckNodes_4$b2c_2_put),
			    .EN_b2c_0_put(vCheckNodes_4$EN_b2c_0_put),
			    .EN_b2c_1_put(vCheckNodes_4$EN_b2c_1_put),
			    .EN_b2c_2_put(vCheckNodes_4$EN_b2c_2_put),
			    .EN_c2b_get(vCheckNodes_4$EN_c2b_get),
			    .RDY_b2c_0_put(vCheckNodes_4$RDY_b2c_0_put),
			    .RDY_b2c_1_put(vCheckNodes_4$RDY_b2c_1_put),
			    .RDY_b2c_2_put(vCheckNodes_4$RDY_b2c_2_put),
			    .c2b_get(vCheckNodes_4$c2b_get),
			    .RDY_c2b_get(vCheckNodes_4$RDY_c2b_get));

  // submodule vCheckNodes_5
  mkCheckNode vCheckNodes_5(.CLK(CLK),
			    .RST_N(RST_N),
			    .b2c_0_put(vCheckNodes_5$b2c_0_put),
			    .b2c_1_put(vCheckNodes_5$b2c_1_put),
			    .b2c_2_put(vCheckNodes_5$b2c_2_put),
			    .EN_b2c_0_put(vCheckNodes_5$EN_b2c_0_put),
			    .EN_b2c_1_put(vCheckNodes_5$EN_b2c_1_put),
			    .EN_b2c_2_put(vCheckNodes_5$EN_b2c_2_put),
			    .EN_c2b_get(vCheckNodes_5$EN_c2b_get),
			    .RDY_b2c_0_put(vCheckNodes_5$RDY_b2c_0_put),
			    .RDY_b2c_1_put(vCheckNodes_5$RDY_b2c_1_put),
			    .RDY_b2c_2_put(vCheckNodes_5$RDY_b2c_2_put),
			    .c2b_get(vCheckNodes_5$c2b_get),
			    .RDY_c2b_get(vCheckNodes_5$RDY_c2b_get));

  // submodule vCheckNodes_6
  mkCheckNode vCheckNodes_6(.CLK(CLK),
			    .RST_N(RST_N),
			    .b2c_0_put(vCheckNodes_6$b2c_0_put),
			    .b2c_1_put(vCheckNodes_6$b2c_1_put),
			    .b2c_2_put(vCheckNodes_6$b2c_2_put),
			    .EN_b2c_0_put(vCheckNodes_6$EN_b2c_0_put),
			    .EN_b2c_1_put(vCheckNodes_6$EN_b2c_1_put),
			    .EN_b2c_2_put(vCheckNodes_6$EN_b2c_2_put),
			    .EN_c2b_get(vCheckNodes_6$EN_c2b_get),
			    .RDY_b2c_0_put(vCheckNodes_6$RDY_b2c_0_put),
			    .RDY_b2c_1_put(vCheckNodes_6$RDY_b2c_1_put),
			    .RDY_b2c_2_put(vCheckNodes_6$RDY_b2c_2_put),
			    .c2b_get(vCheckNodes_6$c2b_get),
			    .RDY_c2b_get(vCheckNodes_6$RDY_c2b_get));

  // rule RL_rlConnect
  assign CAN_FIRE_RL_rlConnect =
	     vBitNodes_0$RDY_b2c_get && vCheckNodes_0$RDY_b2c_0_put &&
	     vCheckNodes_4$RDY_b2c_0_put &&
	     vCheckNodes_6$RDY_b2c_0_put ;
  assign WILL_FIRE_RL_rlConnect = CAN_FIRE_RL_rlConnect ;

  // rule RL_rlConnect_1
  assign CAN_FIRE_RL_rlConnect_1 =
	     vBitNodes_1$RDY_b2c_get && vCheckNodes_0$RDY_b2c_1_put &&
	     vCheckNodes_1$RDY_b2c_0_put &&
	     vCheckNodes_5$RDY_b2c_0_put ;
  assign WILL_FIRE_RL_rlConnect_1 = CAN_FIRE_RL_rlConnect_1 ;

  // rule RL_rlConnect_2
  assign CAN_FIRE_RL_rlConnect_2 =
	     vBitNodes_2$RDY_b2c_get && vCheckNodes_1$RDY_b2c_1_put &&
	     vCheckNodes_6$RDY_b2c_1_put &&
	     vCheckNodes_2$RDY_b2c_0_put ;
  assign WILL_FIRE_RL_rlConnect_2 = CAN_FIRE_RL_rlConnect_2 ;

  // rule RL_rlConnect_3
  assign CAN_FIRE_RL_rlConnect_3 =
	     vBitNodes_3$RDY_b2c_get && vCheckNodes_0$RDY_b2c_2_put &&
	     vCheckNodes_2$RDY_b2c_1_put &&
	     vCheckNodes_3$RDY_b2c_0_put ;
  assign WILL_FIRE_RL_rlConnect_3 = CAN_FIRE_RL_rlConnect_3 ;

  // rule RL_rlConnect_4
  assign CAN_FIRE_RL_rlConnect_4 =
	     vBitNodes_4$RDY_b2c_get && vCheckNodes_1$RDY_b2c_2_put &&
	     vCheckNodes_3$RDY_b2c_1_put &&
	     vCheckNodes_4$RDY_b2c_1_put ;
  assign WILL_FIRE_RL_rlConnect_4 = CAN_FIRE_RL_rlConnect_4 ;

  // rule RL_rlConnect_5
  assign CAN_FIRE_RL_rlConnect_5 =
	     vBitNodes_5$RDY_b2c_get && vCheckNodes_2$RDY_b2c_2_put &&
	     vCheckNodes_4$RDY_b2c_2_put &&
	     vCheckNodes_5$RDY_b2c_1_put ;
  assign WILL_FIRE_RL_rlConnect_5 = CAN_FIRE_RL_rlConnect_5 ;

  // rule RL_rlConnect_6
  assign CAN_FIRE_RL_rlConnect_6 =
	     vBitNodes_6$RDY_b2c_get && vCheckNodes_3$RDY_b2c_2_put &&
	     vCheckNodes_5$RDY_b2c_2_put &&
	     vCheckNodes_6$RDY_b2c_2_put ;
  assign WILL_FIRE_RL_rlConnect_6 = CAN_FIRE_RL_rlConnect_6 ;

  // rule RL_rlConnect_7
  assign CAN_FIRE_RL_rlConnect_7 =
	     vBitNodes_0$RDY_c2b_0_put && vBitNodes_1$RDY_c2b_0_put &&
	     vBitNodes_3$RDY_c2b_0_put &&
	     vCheckNodes_0$RDY_c2b_get ;
  assign WILL_FIRE_RL_rlConnect_7 = CAN_FIRE_RL_rlConnect_7 ;

  // rule RL_rlConnect_8
  assign CAN_FIRE_RL_rlConnect_8 =
	     vBitNodes_1$RDY_c2b_1_put && vBitNodes_2$RDY_c2b_0_put &&
	     vBitNodes_4$RDY_c2b_0_put &&
	     vCheckNodes_1$RDY_c2b_get ;
  assign WILL_FIRE_RL_rlConnect_8 = CAN_FIRE_RL_rlConnect_8 ;

  // rule RL_rlConnect_9
  assign CAN_FIRE_RL_rlConnect_9 =
	     vBitNodes_2$RDY_c2b_1_put && vBitNodes_3$RDY_c2b_1_put &&
	     vBitNodes_5$RDY_c2b_0_put &&
	     vCheckNodes_2$RDY_c2b_get ;
  assign WILL_FIRE_RL_rlConnect_9 = CAN_FIRE_RL_rlConnect_9 ;

  // rule RL_rlConnect_10
  assign CAN_FIRE_RL_rlConnect_10 =
	     vBitNodes_3$RDY_c2b_2_put && vBitNodes_4$RDY_c2b_1_put &&
	     vBitNodes_6$RDY_c2b_0_put &&
	     vCheckNodes_3$RDY_c2b_get ;
  assign WILL_FIRE_RL_rlConnect_10 = CAN_FIRE_RL_rlConnect_10 ;

  // rule RL_rlConnect_11
  assign CAN_FIRE_RL_rlConnect_11 =
	     vBitNodes_4$RDY_c2b_2_put && vBitNodes_0$RDY_c2b_1_put &&
	     vBitNodes_5$RDY_c2b_1_put &&
	     vCheckNodes_4$RDY_c2b_get ;
  assign WILL_FIRE_RL_rlConnect_11 = CAN_FIRE_RL_rlConnect_11 ;

  // rule RL_rlConnect_12
  assign CAN_FIRE_RL_rlConnect_12 =
	     vBitNodes_1$RDY_c2b_2_put && vBitNodes_5$RDY_c2b_2_put &&
	     vBitNodes_6$RDY_c2b_1_put &&
	     vCheckNodes_5$RDY_c2b_get ;
  assign WILL_FIRE_RL_rlConnect_12 = CAN_FIRE_RL_rlConnect_12 ;

  // rule RL_rlConnect_13
  assign CAN_FIRE_RL_rlConnect_13 =
	     vBitNodes_0$RDY_c2b_2_put && vBitNodes_2$RDY_c2b_2_put &&
	     vBitNodes_6$RDY_c2b_2_put &&
	     vCheckNodes_6$RDY_c2b_get ;
  assign WILL_FIRE_RL_rlConnect_13 = CAN_FIRE_RL_rlConnect_13 ;

  // rule RL_rlPutCodeWordIn
  assign CAN_FIRE_RL_rlPutCodeWordIn =
	     vBitNodes_0$RDY_codeIn_put &&
	     vBitNodes_1_RDY_codeIn_put__14_AND_vBitNodes_2_ETC___d126 ;
  assign WILL_FIRE_RL_rlPutCodeWordIn = CAN_FIRE_RL_rlPutCodeWordIn ;

  // rule RL_rlGetDecodedWordOut
  assign CAN_FIRE_RL_rlGetDecodedWordOut =
	     vBitNodes_0$RDY_dataOut_get &&
	     vBitNodes_1_RDY_dataOut_get__37_AND_vBitNodes__ETC___d149 ;
  assign WILL_FIRE_RL_rlGetDecodedWordOut = CAN_FIRE_RL_rlGetDecodedWordOut ;

  // submodule ffI
  assign ffI$D_IN = request_put ;
  assign ffI$ENQ = EN_request_put ;
  assign ffI$DEQ = CAN_FIRE_RL_rlPutCodeWordIn ;
  assign ffI$CLR = 1'b0 ;

  // submodule ffO
  assign ffO$D_IN =
	     { vBitNodes_6$dataOut_get,
	       vBitNodes_5$dataOut_get,
	       vBitNodes_4$dataOut_get,
	       vBitNodes_3$dataOut_get,
	       vBitNodes_2$dataOut_get,
	       vBitNodes_1$dataOut_get,
	       vBitNodes_0$dataOut_get } ;
  assign ffO$ENQ = CAN_FIRE_RL_rlGetDecodedWordOut ;
  assign ffO$DEQ = EN_response_get ;
  assign ffO$CLR = 1'b0 ;

  // submodule vBitNodes_0
  assign vBitNodes_0$c2b_0_put = vCheckNodes_0$c2b_get ;
  assign vBitNodes_0$c2b_1_put = vCheckNodes_4$c2b_get ;
  assign vBitNodes_0$c2b_2_put = vCheckNodes_6$c2b_get ;
  assign vBitNodes_0$codeIn_put = ffI$D_OUT[3:0] ;
  assign vBitNodes_0$EN_c2b_0_put = CAN_FIRE_RL_rlConnect_7 ;
  assign vBitNodes_0$EN_c2b_1_put = CAN_FIRE_RL_rlConnect_11 ;
  assign vBitNodes_0$EN_c2b_2_put = CAN_FIRE_RL_rlConnect_13 ;
  assign vBitNodes_0$EN_b2c_get = CAN_FIRE_RL_rlConnect ;
  assign vBitNodes_0$EN_codeIn_put = CAN_FIRE_RL_rlPutCodeWordIn ;
  assign vBitNodes_0$EN_dataOut_get = CAN_FIRE_RL_rlGetDecodedWordOut ;

  // submodule vBitNodes_1
  assign vBitNodes_1$c2b_0_put = vCheckNodes_0$c2b_get ;
  assign vBitNodes_1$c2b_1_put = vCheckNodes_1$c2b_get ;
  assign vBitNodes_1$c2b_2_put = vCheckNodes_5$c2b_get ;
  assign vBitNodes_1$codeIn_put = ffI$D_OUT[7:4] ;
  assign vBitNodes_1$EN_c2b_0_put = CAN_FIRE_RL_rlConnect_7 ;
  assign vBitNodes_1$EN_c2b_1_put = CAN_FIRE_RL_rlConnect_8 ;
  assign vBitNodes_1$EN_c2b_2_put = CAN_FIRE_RL_rlConnect_12 ;
  assign vBitNodes_1$EN_b2c_get = CAN_FIRE_RL_rlConnect_1 ;
  assign vBitNodes_1$EN_codeIn_put = CAN_FIRE_RL_rlPutCodeWordIn ;
  assign vBitNodes_1$EN_dataOut_get = CAN_FIRE_RL_rlGetDecodedWordOut ;

  // submodule vBitNodes_2
  assign vBitNodes_2$c2b_0_put = vCheckNodes_1$c2b_get ;
  assign vBitNodes_2$c2b_1_put = vCheckNodes_2$c2b_get ;
  assign vBitNodes_2$c2b_2_put = vCheckNodes_6$c2b_get ;
  assign vBitNodes_2$codeIn_put = ffI$D_OUT[11:8] ;
  assign vBitNodes_2$EN_c2b_0_put = CAN_FIRE_RL_rlConnect_8 ;
  assign vBitNodes_2$EN_c2b_1_put = CAN_FIRE_RL_rlConnect_9 ;
  assign vBitNodes_2$EN_c2b_2_put = CAN_FIRE_RL_rlConnect_13 ;
  assign vBitNodes_2$EN_b2c_get = CAN_FIRE_RL_rlConnect_2 ;
  assign vBitNodes_2$EN_codeIn_put = CAN_FIRE_RL_rlPutCodeWordIn ;
  assign vBitNodes_2$EN_dataOut_get = CAN_FIRE_RL_rlGetDecodedWordOut ;

  // submodule vBitNodes_3
  assign vBitNodes_3$c2b_0_put = vCheckNodes_0$c2b_get ;
  assign vBitNodes_3$c2b_1_put = vCheckNodes_2$c2b_get ;
  assign vBitNodes_3$c2b_2_put = vCheckNodes_3$c2b_get ;
  assign vBitNodes_3$codeIn_put = ffI$D_OUT[15:12] ;
  assign vBitNodes_3$EN_c2b_0_put = CAN_FIRE_RL_rlConnect_7 ;
  assign vBitNodes_3$EN_c2b_1_put = CAN_FIRE_RL_rlConnect_9 ;
  assign vBitNodes_3$EN_c2b_2_put = CAN_FIRE_RL_rlConnect_10 ;
  assign vBitNodes_3$EN_b2c_get = CAN_FIRE_RL_rlConnect_3 ;
  assign vBitNodes_3$EN_codeIn_put = CAN_FIRE_RL_rlPutCodeWordIn ;
  assign vBitNodes_3$EN_dataOut_get = CAN_FIRE_RL_rlGetDecodedWordOut ;

  // submodule vBitNodes_4
  assign vBitNodes_4$c2b_0_put = vCheckNodes_1$c2b_get ;
  assign vBitNodes_4$c2b_1_put = vCheckNodes_3$c2b_get ;
  assign vBitNodes_4$c2b_2_put = vCheckNodes_4$c2b_get ;
  assign vBitNodes_4$codeIn_put = ffI$D_OUT[19:16] ;
  assign vBitNodes_4$EN_c2b_0_put = CAN_FIRE_RL_rlConnect_8 ;
  assign vBitNodes_4$EN_c2b_1_put = CAN_FIRE_RL_rlConnect_10 ;
  assign vBitNodes_4$EN_c2b_2_put = CAN_FIRE_RL_rlConnect_11 ;
  assign vBitNodes_4$EN_b2c_get = CAN_FIRE_RL_rlConnect_4 ;
  assign vBitNodes_4$EN_codeIn_put = CAN_FIRE_RL_rlPutCodeWordIn ;
  assign vBitNodes_4$EN_dataOut_get = CAN_FIRE_RL_rlGetDecodedWordOut ;

  // submodule vBitNodes_5
  assign vBitNodes_5$c2b_0_put = vCheckNodes_2$c2b_get ;
  assign vBitNodes_5$c2b_1_put = vCheckNodes_4$c2b_get ;
  assign vBitNodes_5$c2b_2_put = vCheckNodes_5$c2b_get ;
  assign vBitNodes_5$codeIn_put = ffI$D_OUT[23:20] ;
  assign vBitNodes_5$EN_c2b_0_put = CAN_FIRE_RL_rlConnect_9 ;
  assign vBitNodes_5$EN_c2b_1_put = CAN_FIRE_RL_rlConnect_11 ;
  assign vBitNodes_5$EN_c2b_2_put = CAN_FIRE_RL_rlConnect_12 ;
  assign vBitNodes_5$EN_b2c_get = CAN_FIRE_RL_rlConnect_5 ;
  assign vBitNodes_5$EN_codeIn_put = CAN_FIRE_RL_rlPutCodeWordIn ;
  assign vBitNodes_5$EN_dataOut_get = CAN_FIRE_RL_rlGetDecodedWordOut ;

  // submodule vBitNodes_6
  assign vBitNodes_6$c2b_0_put = vCheckNodes_3$c2b_get ;
  assign vBitNodes_6$c2b_1_put = vCheckNodes_5$c2b_get ;
  assign vBitNodes_6$c2b_2_put = vCheckNodes_6$c2b_get ;
  assign vBitNodes_6$codeIn_put = ffI$D_OUT[27:24] ;
  assign vBitNodes_6$EN_c2b_0_put = CAN_FIRE_RL_rlConnect_10 ;
  assign vBitNodes_6$EN_c2b_1_put = CAN_FIRE_RL_rlConnect_12 ;
  assign vBitNodes_6$EN_c2b_2_put = CAN_FIRE_RL_rlConnect_13 ;
  assign vBitNodes_6$EN_b2c_get = CAN_FIRE_RL_rlConnect_6 ;
  assign vBitNodes_6$EN_codeIn_put = CAN_FIRE_RL_rlPutCodeWordIn ;
  assign vBitNodes_6$EN_dataOut_get = CAN_FIRE_RL_rlGetDecodedWordOut ;

  // submodule vCheckNodes_0
  assign vCheckNodes_0$b2c_0_put = vBitNodes_0$b2c_get ;
  assign vCheckNodes_0$b2c_1_put = vBitNodes_1$b2c_get ;
  assign vCheckNodes_0$b2c_2_put = vBitNodes_3$b2c_get ;
  assign vCheckNodes_0$EN_b2c_0_put = CAN_FIRE_RL_rlConnect ;
  assign vCheckNodes_0$EN_b2c_1_put = CAN_FIRE_RL_rlConnect_1 ;
  assign vCheckNodes_0$EN_b2c_2_put = CAN_FIRE_RL_rlConnect_3 ;
  assign vCheckNodes_0$EN_c2b_get = CAN_FIRE_RL_rlConnect_7 ;

  // submodule vCheckNodes_1
  assign vCheckNodes_1$b2c_0_put = vBitNodes_1$b2c_get ;
  assign vCheckNodes_1$b2c_1_put = vBitNodes_2$b2c_get ;
  assign vCheckNodes_1$b2c_2_put = vBitNodes_4$b2c_get ;
  assign vCheckNodes_1$EN_b2c_0_put = CAN_FIRE_RL_rlConnect_1 ;
  assign vCheckNodes_1$EN_b2c_1_put = CAN_FIRE_RL_rlConnect_2 ;
  assign vCheckNodes_1$EN_b2c_2_put = CAN_FIRE_RL_rlConnect_4 ;
  assign vCheckNodes_1$EN_c2b_get = CAN_FIRE_RL_rlConnect_8 ;

  // submodule vCheckNodes_2
  assign vCheckNodes_2$b2c_0_put = vBitNodes_2$b2c_get ;
  assign vCheckNodes_2$b2c_1_put = vBitNodes_3$b2c_get ;
  assign vCheckNodes_2$b2c_2_put = vBitNodes_5$b2c_get ;
  assign vCheckNodes_2$EN_b2c_0_put = CAN_FIRE_RL_rlConnect_2 ;
  assign vCheckNodes_2$EN_b2c_1_put = CAN_FIRE_RL_rlConnect_3 ;
  assign vCheckNodes_2$EN_b2c_2_put = CAN_FIRE_RL_rlConnect_5 ;
  assign vCheckNodes_2$EN_c2b_get = CAN_FIRE_RL_rlConnect_9 ;

  // submodule vCheckNodes_3
  assign vCheckNodes_3$b2c_0_put = vBitNodes_3$b2c_get ;
  assign vCheckNodes_3$b2c_1_put = vBitNodes_4$b2c_get ;
  assign vCheckNodes_3$b2c_2_put = vBitNodes_6$b2c_get ;
  assign vCheckNodes_3$EN_b2c_0_put = CAN_FIRE_RL_rlConnect_3 ;
  assign vCheckNodes_3$EN_b2c_1_put = CAN_FIRE_RL_rlConnect_4 ;
  assign vCheckNodes_3$EN_b2c_2_put = CAN_FIRE_RL_rlConnect_6 ;
  assign vCheckNodes_3$EN_c2b_get = CAN_FIRE_RL_rlConnect_10 ;

  // submodule vCheckNodes_4
  assign vCheckNodes_4$b2c_0_put = vBitNodes_0$b2c_get ;
  assign vCheckNodes_4$b2c_1_put = vBitNodes_4$b2c_get ;
  assign vCheckNodes_4$b2c_2_put = vBitNodes_5$b2c_get ;
  assign vCheckNodes_4$EN_b2c_0_put = CAN_FIRE_RL_rlConnect ;
  assign vCheckNodes_4$EN_b2c_1_put = CAN_FIRE_RL_rlConnect_4 ;
  assign vCheckNodes_4$EN_b2c_2_put = CAN_FIRE_RL_rlConnect_5 ;
  assign vCheckNodes_4$EN_c2b_get = CAN_FIRE_RL_rlConnect_11 ;

  // submodule vCheckNodes_5
  assign vCheckNodes_5$b2c_0_put = vBitNodes_1$b2c_get ;
  assign vCheckNodes_5$b2c_1_put = vBitNodes_5$b2c_get ;
  assign vCheckNodes_5$b2c_2_put = vBitNodes_6$b2c_get ;
  assign vCheckNodes_5$EN_b2c_0_put = CAN_FIRE_RL_rlConnect_1 ;
  assign vCheckNodes_5$EN_b2c_1_put = CAN_FIRE_RL_rlConnect_5 ;
  assign vCheckNodes_5$EN_b2c_2_put = CAN_FIRE_RL_rlConnect_6 ;
  assign vCheckNodes_5$EN_c2b_get = CAN_FIRE_RL_rlConnect_12 ;

  // submodule vCheckNodes_6
  assign vCheckNodes_6$b2c_0_put = vBitNodes_0$b2c_get ;
  assign vCheckNodes_6$b2c_1_put = vBitNodes_2$b2c_get ;
  assign vCheckNodes_6$b2c_2_put = vBitNodes_6$b2c_get ;
  assign vCheckNodes_6$EN_b2c_0_put = CAN_FIRE_RL_rlConnect ;
  assign vCheckNodes_6$EN_b2c_1_put = CAN_FIRE_RL_rlConnect_2 ;
  assign vCheckNodes_6$EN_b2c_2_put = CAN_FIRE_RL_rlConnect_6 ;
  assign vCheckNodes_6$EN_c2b_get = CAN_FIRE_RL_rlConnect_13 ;

  // remaining internal signals
  assign vBitNodes_1_RDY_codeIn_put__14_AND_vBitNodes_2_ETC___d126 =
	     vBitNodes_1$RDY_codeIn_put && vBitNodes_2$RDY_codeIn_put &&
	     vBitNodes_3$RDY_codeIn_put &&
	     vBitNodes_4$RDY_codeIn_put &&
	     vBitNodes_5$RDY_codeIn_put &&
	     vBitNodes_6$RDY_codeIn_put &&
	     ffI$EMPTY_N ;
  assign vBitNodes_1_RDY_dataOut_get__37_AND_vBitNodes__ETC___d149 =
	     vBitNodes_1$RDY_dataOut_get && vBitNodes_2$RDY_dataOut_get &&
	     vBitNodes_3$RDY_dataOut_get &&
	     vBitNodes_4$RDY_dataOut_get &&
	     vBitNodes_5$RDY_dataOut_get &&
	     vBitNodes_6$RDY_dataOut_get &&
	     ffO$FULL_N ;
endmodule  // mkLdpcCore

