//
// Generated by Bluespec Compiler, version 2018.10.beta1 (build e1df8052c, 2018-10-17)
//
// On Tue Apr 16 14:00:56 IST 2019
//
//
// Ports:
// Name                         I/O  size props
// fnBitNodeProcessing            O     4
// fnBitNodeProcessing_x          I    12
//
// Combinational paths from inputs to outputs:
//   fnBitNodeProcessing_x -> fnBitNodeProcessing
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_fnBitNodeProcessing(fnBitNodeProcessing_x,
				  fnBitNodeProcessing);
  // value method fnBitNodeProcessing
  input  [11 : 0] fnBitNodeProcessing_x;
  output [3 : 0] fnBitNodeProcessing;

  // signals for module outputs
  wire [3 : 0] fnBitNodeProcessing;

  // remaining internal signals
  wire [3 : 0] x__h133;

  // value method fnBitNodeProcessing
  assign fnBitNodeProcessing = x__h133 ^ fnBitNodeProcessing_x[11:8] ;

  // remaining internal signals
  assign x__h133 = fnBitNodeProcessing_x[3:0] ^ fnBitNodeProcessing_x[7:4] ;
endmodule  // module_fnBitNodeProcessing

