//
// Generated by Bluespec Compiler, version 2018.10.beta1 (build e1df8052c, 2018-10-17)
//
// On Tue Apr 16 14:00:56 IST 2019
//
//
// Ports:
// Name                         I/O  size props
// fnCheckNodeProcessing          O     4
// fnCheckNodeProcessing_x        I    12
//
// Combinational paths from inputs to outputs:
//   fnCheckNodeProcessing_x -> fnCheckNodeProcessing
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_fnCheckNodeProcessing(fnCheckNodeProcessing_x,
				    fnCheckNodeProcessing);
  // value method fnCheckNodeProcessing
  input  [11 : 0] fnCheckNodeProcessing_x;
  output [3 : 0] fnCheckNodeProcessing;

  // signals for module outputs
  wire [3 : 0] fnCheckNodeProcessing;

  // remaining internal signals
  wire [3 : 0] x__h133;

  // value method fnCheckNodeProcessing
  assign fnCheckNodeProcessing = x__h133 ^ fnCheckNodeProcessing_x[11:8] ;

  // remaining internal signals
  assign x__h133 =
	     fnCheckNodeProcessing_x[3:0] ^ fnCheckNodeProcessing_x[7:4] ;
endmodule  // module_fnCheckNodeProcessing

